PDA-43: List BPM Groups
entando/pda-core-engine pull request #11
Opened 2019-12-03 01:25 UTC by werbth

Jira ticket: https://jira.entando.org/browse/PDA-43

2019-12-03 01:26 UTC, entando-service commented
All is well

2019-12-03 14:32 UTC, ffleandro requested changes

2019-12-03 14:32 UTC, ffleandro commented on src/main/java/org/entando/plugins/pda/core/service/group/GroupService.java
> +    List<String> list(Connection connection, String containerId, String processId);
Should we use an id concatenated, same as we are using on Process Diagram endpoint?

2019-12-03 19:34 UTC, entando-service commented
All is well

2019-12-04 11:17 UTC, ffleandro approved these changes

2019-12-04 11:21 UTC, merged